---
services:
  - service:
      service-id: SERVICE1
      service-description: Send Money
      service-time: 11
  - service:
      service-id: SERVICE2
      service-description: Pay Bill
      service-time: 12
  - service:
      service-id: SERVICE3
      service-description: Send Letter
      service-time: 13
  - service:
      service-id: SERVICE4
      service-description: Ship Parcel
      service-time: 14
  - service:
      service-id: SERVICE5
      service-description: Return Parcel
      service-time: 15
desks:
  - desk:
      desk-id: 1
      offered-services:
        - SERVICE1
        - SERVICE2
  - desk:
      desk-id: 2
      offered-services:
        - SERVICE1
        - SERVICE3
  - desk:
      desk-id: 3
      offered-services:
        - SERVICE1
        - SERVICE2
  - desk:
      desk-id: 4
      offered-services:
        - SERVICE1
        - SERVICE4
        - SERVICE5
...